### ISSUE TITLE
Thank you for your material. Can I get code to get angle with acc, gyro value from bmi270 sensor?

### ISSUE THREAD

**Issue by leeyunhome** [CoRoLab-Berlin/bmi270_python#1]
Hello, @ksomml @ma-weiss 

I'm looking for some code for getting angle value using bmi270 imu sensor.
Thank you for your material. Can I get code to get angle with acc, gyro value from bmi270 sensor?

Thank you.

**Comment by ksomml** [comment]
Hello @leeyunhome,
if you mean that you want the orientation of the IMU, you could use [VQF](https://vqf.readthedocs.io/en/latest/) to get the Quaternion orientation.
